
 Student Name: Matthew Cheng

 Student ID: 107990014
<br /><br />
Due Date: October 26, 2021

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statistics

from sklearn import preprocessing

In [4]:
data = pd.read_table('/content/household_power_consumption.zip', 
                     compression='zip', sep=';', 
                     low_memory=False, header=0, index_col=False,
                     parse_dates=[0])

In [5]:
df = pd.DataFrame(data, dtype=None)
df.replace('?', np.nan,inplace=True)
df

Date      Time  ... Sub_metering_2 Sub_metering_3
0       2006-12-16  17:24:00  ...          1.000           17.0
1       2006-12-16  17:25:00  ...          1.000           16.0
2       2006-12-16  17:26:00  ...          2.000           17.0
3       2006-12-16  17:27:00  ...          1.000           17.0
4       2006-12-16  17:28:00  ...          1.000           17.0
...            ...       ...  ...            ...            ...
2075254 2010-11-26  20:58:00  ...          0.000            0.0
2075255 2010-11-26  20:59:00  ...          0.000            0.0
2075256 2010-11-26  21:00:00  ...          0.000            0.0
2075257 2010-11-26  21:01:00  ...          0.000            0.0
2075258 2010-11-26  21:02:00  ...          0.000            0.0

[2075259 rows x 9 columns]

In [6]:
df.fillna(0)

Date      Time  ... Sub_metering_2 Sub_metering_3
0       2006-12-16  17:24:00  ...          1.000           17.0
1       2006-12-16  17:25:00  ...          1.000           16.0
2       2006-12-16  17:26:00  ...          2.000           17.0
3       2006-12-16  17:27:00  ...          1.000           17.0
4       2006-12-16  17:28:00  ...          1.000           17.0
...            ...       ...  ...            ...            ...
2075254 2010-11-26  20:58:00  ...          0.000            0.0
2075255 2010-11-26  20:59:00  ...          0.000            0.0
2075256 2010-11-26  21:00:00  ...          0.000            0.0
2075257 2010-11-26  21:01:00  ...          0.000            0.0
2075258 2010-11-26  21:02:00  ...          0.000            0.0

[2075259 rows x 9 columns]

In [7]:
#convert values to float format

df["Global_active_power"]   = df["Global_active_power"].astype(float)
df["Global_reactive_power"] = df["Global_reactive_power"].astype(float)
df["Voltage"]               = df["Voltage"].astype(float)
df["Global_intensity"]      = df["Global_intensity"].astype(float)
df["Sub_metering_1"]        = df["Sub_metering_1"].astype(float)
df["Sub_metering_2"]        = df["Sub_metering_2"].astype(float)
df["Sub_metering_3"]        = df["Sub_metering_3"].astype(float)

In [8]:
print("Max Values\n")
df.iloc[:,2:6].max()


Max Values



Global_active_power       11.122
Global_reactive_power      1.390
Voltage                  254.150
Global_intensity          48.400
dtype: float64

In [9]:
print("Min Values\n")
df.iloc[:,2:6].min()


Min Values



Global_active_power        0.076
Global_reactive_power      0.000
Voltage                  223.200
Global_intensity           0.200
dtype: float64

In [10]:
print("Count\n")
df.iloc[:,2:6].count()


Count



Global_active_power      2049280
Global_reactive_power    2049280
Voltage                  2049280
Global_intensity         2049280
dtype: int64

In [11]:
print("Mean Values\n")
df.iloc[:,2:6].mean()


Mean Values



Global_active_power        1.091615
Global_reactive_power      0.123714
Voltage                  240.839858
Global_intensity           4.627759
dtype: float64

In [12]:
print("Standard Deviation\n")
df.iloc[:,2:6].std()


Standard Deviation



Global_active_power      1.057294
Global_reactive_power    0.112722
Voltage                  3.239987
Global_intensity         4.444396
dtype: float64

In [13]:
minmax_rescale = preprocessing.MinMaxScaler()
minmax_normalize = minmax_rescale.fit_transform(df.iloc[:,2:6])
print(minmax_normalize)

[[0.37479631 0.30071942 0.37609047 0.37759336]
 [0.47836321 0.31366906 0.33699515 0.47302905]
 [0.47963064 0.35827338 0.32600969 0.47302905]
 ...
 [0.0780373  0.         0.53699515 0.0746888 ]
 [0.07767518 0.         0.53311793 0.0746888 ]
 [0.07749412 0.         0.52827141 0.0746888 ]]


In [14]:
df = pd.DataFrame(minmax_normalize)
df.to_csv('normalized_107990014.csv')

In [15]:
from IPython.display import FileLink
FileLink('normalized_107990014.csv')

/content/normalized.csv